# Generated by Django 5.0.6 on 2025-07-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка в процентах (например, 10.00 для 10%)', max_digits=5),
        ),
    ]
