# Generated by Django 5.2.5 on 2025-08-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'Фотки для галереи'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('decorative', 'Декоративная косметика'), ('skincare', 'Уходовая косметика')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Скидка в процентах (например, 10.00 для 10%)', max_digits=5, verbose_name='Скидка на этот товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID для связки с тг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('lipstick', 'Помады'), ('eyeshadow', 'Тени'), ('mascara', 'Тушь'), ('none', 'Без подкатегории')], default='none', max_length=20, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/extra/', verbose_name='Фотки для галереи'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Продукт'),
        ),
    ]
