# Generated by Django 5.2.5 on 2025-08-29 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bonuscard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuscard',
            options={'verbose_name_plural': 'Бонусные карты'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='bonus_points',
            field=models.FloatField(default=0, verbose_name='Количество бонусов'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='discount_percent',
            field=models.IntegerField(default=10, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='bonuscard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
